language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

before_script:
  - go get github.com/fortytw2/leaktest
  - go get github.com/davecgh/go-spew/spew
  - go tool vet -all -composites=false -shadow=true aat client transport examples nexusd transport wamp router

script:
  - go build ./examples/...
  - go test ./nexusd/...
  - go test -v -race ./wamp/...
  - go test -v -race ./transport/...
  - go test -v -race ./router/...
  - go test -v -race ./client/...
  - go test -v -race ./aat/...
  - go test -v -race ./aat -scheme=ws -compress
  - go test -v ./aat -scheme=wss -serialize=msgpack
  - go test -v ./aat -scheme=tcps
